// import 'dart:ui';
// import 'package:flutter/material.dart';
// import 'package:mygallery/core/style/size.dart';

// /// Helper class for managing themes and colors.
// class ThemeHelper {
//   // The current app theme
// //   var _appTheme = PrefUtils().getThemeData();

// // // A map of custom color themes supported by the app
// //   Map<String, PrimaryColors> _supportedCustomColor = {
// //     'primary': PrimaryColors()
// //   };

// // // A map of color schemes supported by the app
// //   Map<String, ColorScheme> _supportedColorScheme = {
// //     'primary': ColorSchemes.primaryColorScheme
// //   };

//   /// Returns the primary colors for the current theme.
//   // PrimaryColors _getThemeColors() {
//   //   //throw exception to notify given theme is not found or not generated by the generatorif (!_supportedCustomColor.containsKey(_appTheme)){  throw Exception(               "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");      } //return theme from map
//   //   return _supportedCustomColor[_appTheme] ?? PrimaryColors();
//   // }

//   // /// Returns the current theme data.
//   // ThemeData _getThemeData() {
//   //   //throw exception to notify given theme is not found or not generated by the generator if (!_supportedColorScheme.containsKey(_appTheme)){   throw Exception(                "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");       }  //return theme from map
//     // var colorScheme =
//     //     _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
//     return ThemeData(
//       visualDensity: VisualDensity.standard,
//       colorScheme: colorScheme,
//       textTheme: TextThemes.textTheme(colorScheme),
//       scaffoldBackgroundColor: colorScheme.onPrimaryContainer.withOpacity(1),
//       elevatedButtonTheme: ElevatedButtonThemeData(
//         style: ElevatedButton.styleFrom(
//           shape: RoundedRectangleBorder(
//             borderRadius: BorderRadius.circular(16),
//           ),
//           visualDensity: const VisualDensity(
//             vertical: -4,
//             horizontal: -4,
//           ),
//           padding: EdgeInsets.zero,
//         ),
//       ),
//     );
//   }

//   /// Returns the primary colors for the current theme.
//   PrimaryColors themeColor() => _getThemeColors();

//   /// Returns the current theme data.
//   ThemeData themeData() => _getThemeData();
// }

// /// Class containing the supported text theme styles.
// class TextThemes {
//   static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
//         displayMedium: TextStyle(
//           color: colorScheme.onPrimary,
//           fontSize: 50.fSize,
//           fontFamily: 'Segoe UI',
//           fontWeight: FontWeight.w700,
//         ),
//         headlineLarge: TextStyle(
//           color: colorScheme.onPrimary,
//           fontSize: 32.fSize,
//           fontFamily: 'Baloo Thambi 2',
//           fontWeight: FontWeight.w600,
//         ),
//         headlineMedium: TextStyle(
//           color: colorScheme.onPrimary,
//           fontSize: 27.fSize,
//           fontFamily: 'Segoe UI',
//           fontWeight: FontWeight.w700,
//         ),
//         titleLarge: TextStyle(
//           color: colorScheme.onPrimary,
//           fontSize: 20.fSize,
//           fontFamily: 'Baloo Thambi 2',
//           fontWeight: FontWeight.w600,
//         ),
//         titleMedium: TextStyle(
//           color: colorScheme.onPrimaryContainer.withOpacity(1),
//           fontSize: 18.fSize,
//           fontFamily: 'Segoe UI',
//           fontWeight: FontWeight.w700,
//         ),
//       );
// }

// /// Class containing the supported color schemes.
// class ColorSchemes {
//   static final primaryColorScheme = ColorScheme.light(
//     // Primary colors
//     primary: Color(0XFF7BB3FF),
//     secondaryContainer: Color(0XFFF7F7F7),

//     // On colors(text colors)
//     onPrimary: Color(0XFF4A4A4A),
//     onPrimaryContainer: Color(0X66FFFFFF),
//   );
// }

// /// Class containing custom colors for a primary theme.
// class PrimaryColors {
//   // Amber
//   Color get amber300 => Color(0XFFFFCD62);

//   // Black
//   Color get black900 => Color(0XFF000000);
//   Color get black90040 => Color(0X40000000);

//   // Blue
//   Color get blue50 => Color(0XFFEBF6FF);

//   // BlueGray
//   Color get blueGray100 => Color(0XFFD9D9D9);
//   Color get blueGray400 => Color(0XFF888888);

//   // DeepOrange
//   Color get deepOrange100 => Color(0XFFFDB2B2);

//   // DeepPurple
//   Color get deepPurple100 => Color(0XFFDDCDFF);

//   // Gray
//   Color get gray50 => Color(0XFFFAFAFA);
//   Color get gray500 => Color(0XFF988F8C);
//   Color get gray50001 => Color(0XFF9D9491);

//   // Orange
//   Color get orange400 => Color(0XFFFEA12F);

//   // Purple
//   Color get purple50 => Color(0XFFEFD8F9);
// }

// PrimaryColors get appTheme => ThemeHelper().themeColor();
// ThemeData get theme => ThemeHelper().themeData();
